
server:
  port: 8001
eureka:
  instance:
    ip-address: 192.168.0.108
    hostname: eureka
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka:80/eureka
spring:
  application:
    name: discovery-client
