server:
  port: 8771
spring:
  application:
    name: produce-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
        loggerLeveL: basic

