spring:
  application:
    name: order-server
server:
  port: 8772
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
produce-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
        loggerLevel: basic
  hystrix:
    enabled: true