spring:
  application:
    name: order-server
server:
  port: 8772
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
produce-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
