server:
  port: 7601

eureka:
  instance:
    hostname: eureka1
  server:
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false # 设为false 关闭自我保护
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka2:7602/eureka/